namespace Backend.DTOs.Register
{
    public class RegisterResponseDto
    {
        public int Id { get; set; }      // User ID generated by database
        public string Name { get; set; }
        public string Email { get; set; }
        public string Token { get; set; } // JWT token issued after registration
    }
}
